### ISSUE TITLE
t/ConvertPage.t fails if Text::Markdown is not installed

### ISSUE THREAD

**Issue by eserte** [Jinzang/App-Followme#2]
It seems that the number of skipped tests is not correct:
```
$ perl5.22.0t -Mblib t/ConvertPage.t
1..5
ok 1 # skip Text::Markdown not installed
ok 2 # skip Text::Markdown not installed
# Looks like you planned 5 tests but ran 2.
```

**Comment by eserte** [comment]
t/CreateGallery.t and t/ZFunctional.t may also fail, but I did not research why.

**Comment by Jinzang** [comment]
I've uploaded a new version of App::Followme, 1.14 to github and cpan. It uses Test::Requires instead of skip blocks and should fix the problem.

**Comment by eserte** [comment]
Seems to be fine now!
